config/routes.rb
Rails.application.routes.draw do
  # resources :comments
  root "profiles#index"
  
  devise_for :users, controllers: { registrations: 'users/registrations'}
  resources :users do
    member do
      put :change_role_to_seller
    end
  end
  
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  get 'cart/show'
  get "/profiles", to: "profiles#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  authenticate :user do
    resources :products 
    post 'buy', to: 'buy_products#create', as: :buy
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    mount_uploader :avatar, AvatarUploader
    has_many :orderables
    has_many :carts, through: :orderables
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :set_product, only: [:show, :edit, :update, :destroy] 
  before_action :require_admin, only: [:edit, :update, :destroy]
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params.merge(user_id: current_user.id))
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    end
  end

  def edit
    authorize @product
    if @product.edit(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
  end
end

  def update
    authorize @product
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end 
    def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end
  
  private
  def set_product
    @product = Product.find(params[:id])
  end
end

def require_admin
  if current_user.role == 'user'
    redirect_to root_path, alert: 'У вас нет прав для выполнения этого действия'
  end
end

 def product_params
  params.require(:product).permit(:name, :description, :price, :rating, :avatar)
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.label :avatar, style: "display: block" %>
    <%= form.file_field :avatar %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= product.rating %>
  </p>

  
  <%= form_with(url: cart_add_path) do |f| %>
    <%= f.hidden_field :id, value: product.id %>
    <%= f.number_field :quantity, value: 0, min: 1 %>
    <%= f.submit "Add To Cart" %>
  <% end %>

</div>

app/views/products/create.html.erb
<h1>Create Product</h1>

<%= form_for @product, html: { multipart: true } do |f| %>
<% user_id = current_user.id%>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', products_path %>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>EDIT PRODUCT</h1>
<hr/>

<%= form_for @product, html: { multipart: true } do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', products_path, style: "back_btn" %>
<div><%= button_to "Delete product", product_path(@product), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class:"cancel-account"%></div>

app/views/products/index.html.erb
<div class="product_header">

  <h1> YOUR PRODUCTS <h1>
  <%= link_to image_tag("arrows/home.png", class: "home_img"), root_path %>
</div>
<hr/>
<% @products.each do |product| %>
  <div class = "product_image-container">
    <p><%= product.name %></p> 
     <%= image_tag product.avatar.url, class:"product_image"%>
     <br/>
  <%= link_to "Show Product", product_path(product), class: "product_show-btn" %>
     </div>
      <%= form_with(url: cart_add_path) do |f| %>
    <%= f.hidden_field :id, value: product.id %>
    <%= f.number_field :quantity, value: 0, min: 1 %>
    <%= f.submit "Add To Cart" %>
  <% end %>
<%# <%= button_to 'Купить', buy_path(product), method: :post, params: product.id%>
<% end %>
<br/>
<% if current_user.role=="seller"  %>
<%= link_to "Create Product", new_product_path, class: "product_create-btn" %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_for @product, html: { multipart: true } do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="product_header">
<h1 >PRODUCTS</h1>
<%= link_to image_tag("arrows/home.png", class: "home_img"), products_path %>
</div>
<hr/>
    <div class = "product">
            <%= image_tag @product.avatar.url, class:"product_img"%> 

        <div class= "product_text">
            <div class = "product_name">
                <h2>NAME</h2>
                <p><%= @product.name %></p>
                <hr/>
            </div>
            <div class="product_description">
                <h2>DESCRIPTION</h2>
                <p><%= @product.description %></p>
                <hr/>
            </div>
            <div class="product_price">
                <h2>PRICE</h2>
                <p><%= @product.price %></p>
                <hr/>
            </div>
            <div class="product_rating">
                <h2>RATING</h2>
                <p><%= @product.rating %></p>
                <hr/>
            </div>
        </div>
    </div>
    <% if current_user.role=="seller"  %>
     <%= link_to "Edit Product", edit_product_path, class: "product_edit" %>
<% end %>

    
    
  

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>